//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl", ConfigurationName="ndfdXMLPortType")]
public interface ndfdXMLPortType
{
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlOut")]
    string NDFDgen(decimal latitude, decimal longitude, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlOut")]
    System.Threading.Tasks.Task<string> NDFDgenAsync(decimal latitude, decimal longitude, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenLatLonList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlOut")]
    string NDFDgenLatLonList(string listLatLon, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenLatLonList", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlOut")]
    System.Threading.Tasks.Task<string> NDFDgenLatLonListAsync(string listLatLon, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSubgrid", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string LatLonListSubgrid(decimal lowerLeftLatitude, decimal lowerLeftLongitude, decimal upperRightLatitude, decimal upperRightLongitude, decimal resolution);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSubgrid", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> LatLonListSubgridAsync(decimal lowerLeftLatitude, decimal lowerLeftLongitude, decimal upperRightLatitude, decimal upperRightLongitude, decimal resolution);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListLine", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string LatLonListLine(decimal endPoint1Lat, decimal endPoint1Lon, decimal endPoint2Lat, decimal endPoint2Lon);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListLine", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> LatLonListLineAsync(decimal endPoint1Lat, decimal endPoint1Lon, decimal endPoint2Lat, decimal endPoint2Lon);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string LatLonListZipCode(string zipCodeList);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> LatLonListZipCodeAsync(string zipCodeList);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListCityNames", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string LatLonListCityNames([System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string displayLevel);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListCityNames", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> LatLonListCityNamesAsync([System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string displayLevel);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSquare", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string LatLonListSquare(decimal centerPointLat, decimal centerPointLon, decimal distanceLat, decimal distanceLon, decimal resolution);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSquare", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> LatLonListSquareAsync(decimal centerPointLat, decimal centerPointLon, decimal distanceLat, decimal distanceLon, decimal resolution);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#CornerPoints", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    string CornerPoints(string sector);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#CornerPoints", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="listLatLonOut")]
    System.Threading.Tasks.Task<string> CornerPointsAsync(string sector);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlLatLonList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwGmlOut")]
    string GmlLatLonList(string listLatLon, System.DateTime requestedTime, string featureType, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlLatLonList", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwGmlOut")]
    System.Threading.Tasks.Task<string> GmlLatLonListAsync(string listLatLon, System.DateTime requestedTime, string featureType, weatherParametersType weatherParameters);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlTimeSeries", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwGmlOut")]
    string GmlTimeSeries(string listLatLon, System.DateTime startTime, System.DateTime endTime, string compType, string featureType, string propertyName);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlTimeSeries", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwGmlOut")]
    System.Threading.Tasks.Task<string> GmlTimeSeriesAsync(string listLatLon, System.DateTime startTime, System.DateTime endTime, string compType, string featureType, string propertyName);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlByDayOut")]
    string NDFDgenByDay(decimal latitude, decimal longitude, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string numDays, string Unit, string format);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlByDayOut")]
    System.Threading.Tasks.Task<string> NDFDgenByDayAsync(decimal latitude, decimal longitude, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string numDays, string Unit, string format);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDayLatLonLis" +
        "t", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlByDayOut")]
    string NDFDgenByDayLatLonList(string listLatLon, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string numDays, string Unit, string format);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDayLatLonLis" +
        "t", ReplyAction="*")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="dwmlByDayOut")]
    System.Threading.Tasks.Task<string> NDFDgenByDayLatLonListAsync(string listLatLon, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime startDate, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string numDays, string Unit, string format);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl")]
public partial class weatherParametersType
{
    
    private bool maxtField;
    
    private bool mintField;
    
    private bool tempField;
    
    private bool dewField;
    
    private bool pop12Field;
    
    private bool qpfField;
    
    private bool skyField;
    
    private bool snowField;
    
    private bool wspdField;
    
    private bool wdirField;
    
    private bool wxField;
    
    private bool wavehField;
    
    private bool iconsField;
    
    private bool rhField;
    
    private bool apptField;
    
    private bool incw34Field;
    
    private bool incw50Field;
    
    private bool incw64Field;
    
    private bool cumw34Field;
    
    private bool cumw50Field;
    
    private bool cumw64Field;
    
    private bool critfireoField;
    
    private bool dryfireoField;
    
    private bool conhazoField;
    
    private bool ptornadoField;
    
    private bool phailField;
    
    private bool ptstmwindsField;
    
    private bool pxtornadoField;
    
    private bool pxhailField;
    
    private bool pxtstmwindsField;
    
    private bool ptotsvrtstmField;
    
    private bool pxtotsvrtstmField;
    
    private bool tmpabv14dField;
    
    private bool tmpblw14dField;
    
    private bool tmpabv30dField;
    
    private bool tmpblw30dField;
    
    private bool tmpabv90dField;
    
    private bool tmpblw90dField;
    
    private bool prcpabv14dField;
    
    private bool prcpblw14dField;
    
    private bool prcpabv30dField;
    
    private bool prcpblw30dField;
    
    private bool prcpabv90dField;
    
    private bool prcpblw90dField;
    
    private bool precipa_rField;
    
    private bool sky_rField;
    
    private bool temp_rField;
    
    private bool td_rField;
    
    private bool wdir_rField;
    
    private bool wspd_rField;
    
    private bool wwaField;
    
    private bool wgustField;
    
    private bool iceaccumField;
    
    /// <remarks/>
    public bool maxt
    {
        get
        {
            return this.maxtField;
        }
        set
        {
            this.maxtField = value;
        }
    }
    
    /// <remarks/>
    public bool mint
    {
        get
        {
            return this.mintField;
        }
        set
        {
            this.mintField = value;
        }
    }
    
    /// <remarks/>
    public bool temp
    {
        get
        {
            return this.tempField;
        }
        set
        {
            this.tempField = value;
        }
    }
    
    /// <remarks/>
    public bool dew
    {
        get
        {
            return this.dewField;
        }
        set
        {
            this.dewField = value;
        }
    }
    
    /// <remarks/>
    public bool pop12
    {
        get
        {
            return this.pop12Field;
        }
        set
        {
            this.pop12Field = value;
        }
    }
    
    /// <remarks/>
    public bool qpf
    {
        get
        {
            return this.qpfField;
        }
        set
        {
            this.qpfField = value;
        }
    }
    
    /// <remarks/>
    public bool sky
    {
        get
        {
            return this.skyField;
        }
        set
        {
            this.skyField = value;
        }
    }
    
    /// <remarks/>
    public bool snow
    {
        get
        {
            return this.snowField;
        }
        set
        {
            this.snowField = value;
        }
    }
    
    /// <remarks/>
    public bool wspd
    {
        get
        {
            return this.wspdField;
        }
        set
        {
            this.wspdField = value;
        }
    }
    
    /// <remarks/>
    public bool wdir
    {
        get
        {
            return this.wdirField;
        }
        set
        {
            this.wdirField = value;
        }
    }
    
    /// <remarks/>
    public bool wx
    {
        get
        {
            return this.wxField;
        }
        set
        {
            this.wxField = value;
        }
    }
    
    /// <remarks/>
    public bool waveh
    {
        get
        {
            return this.wavehField;
        }
        set
        {
            this.wavehField = value;
        }
    }
    
    /// <remarks/>
    public bool icons
    {
        get
        {
            return this.iconsField;
        }
        set
        {
            this.iconsField = value;
        }
    }
    
    /// <remarks/>
    public bool rh
    {
        get
        {
            return this.rhField;
        }
        set
        {
            this.rhField = value;
        }
    }
    
    /// <remarks/>
    public bool appt
    {
        get
        {
            return this.apptField;
        }
        set
        {
            this.apptField = value;
        }
    }
    
    /// <remarks/>
    public bool incw34
    {
        get
        {
            return this.incw34Field;
        }
        set
        {
            this.incw34Field = value;
        }
    }
    
    /// <remarks/>
    public bool incw50
    {
        get
        {
            return this.incw50Field;
        }
        set
        {
            this.incw50Field = value;
        }
    }
    
    /// <remarks/>
    public bool incw64
    {
        get
        {
            return this.incw64Field;
        }
        set
        {
            this.incw64Field = value;
        }
    }
    
    /// <remarks/>
    public bool cumw34
    {
        get
        {
            return this.cumw34Field;
        }
        set
        {
            this.cumw34Field = value;
        }
    }
    
    /// <remarks/>
    public bool cumw50
    {
        get
        {
            return this.cumw50Field;
        }
        set
        {
            this.cumw50Field = value;
        }
    }
    
    /// <remarks/>
    public bool cumw64
    {
        get
        {
            return this.cumw64Field;
        }
        set
        {
            this.cumw64Field = value;
        }
    }
    
    /// <remarks/>
    public bool critfireo
    {
        get
        {
            return this.critfireoField;
        }
        set
        {
            this.critfireoField = value;
        }
    }
    
    /// <remarks/>
    public bool dryfireo
    {
        get
        {
            return this.dryfireoField;
        }
        set
        {
            this.dryfireoField = value;
        }
    }
    
    /// <remarks/>
    public bool conhazo
    {
        get
        {
            return this.conhazoField;
        }
        set
        {
            this.conhazoField = value;
        }
    }
    
    /// <remarks/>
    public bool ptornado
    {
        get
        {
            return this.ptornadoField;
        }
        set
        {
            this.ptornadoField = value;
        }
    }
    
    /// <remarks/>
    public bool phail
    {
        get
        {
            return this.phailField;
        }
        set
        {
            this.phailField = value;
        }
    }
    
    /// <remarks/>
    public bool ptstmwinds
    {
        get
        {
            return this.ptstmwindsField;
        }
        set
        {
            this.ptstmwindsField = value;
        }
    }
    
    /// <remarks/>
    public bool pxtornado
    {
        get
        {
            return this.pxtornadoField;
        }
        set
        {
            this.pxtornadoField = value;
        }
    }
    
    /// <remarks/>
    public bool pxhail
    {
        get
        {
            return this.pxhailField;
        }
        set
        {
            this.pxhailField = value;
        }
    }
    
    /// <remarks/>
    public bool pxtstmwinds
    {
        get
        {
            return this.pxtstmwindsField;
        }
        set
        {
            this.pxtstmwindsField = value;
        }
    }
    
    /// <remarks/>
    public bool ptotsvrtstm
    {
        get
        {
            return this.ptotsvrtstmField;
        }
        set
        {
            this.ptotsvrtstmField = value;
        }
    }
    
    /// <remarks/>
    public bool pxtotsvrtstm
    {
        get
        {
            return this.pxtotsvrtstmField;
        }
        set
        {
            this.pxtotsvrtstmField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpabv14d
    {
        get
        {
            return this.tmpabv14dField;
        }
        set
        {
            this.tmpabv14dField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpblw14d
    {
        get
        {
            return this.tmpblw14dField;
        }
        set
        {
            this.tmpblw14dField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpabv30d
    {
        get
        {
            return this.tmpabv30dField;
        }
        set
        {
            this.tmpabv30dField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpblw30d
    {
        get
        {
            return this.tmpblw30dField;
        }
        set
        {
            this.tmpblw30dField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpabv90d
    {
        get
        {
            return this.tmpabv90dField;
        }
        set
        {
            this.tmpabv90dField = value;
        }
    }
    
    /// <remarks/>
    public bool tmpblw90d
    {
        get
        {
            return this.tmpblw90dField;
        }
        set
        {
            this.tmpblw90dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpabv14d
    {
        get
        {
            return this.prcpabv14dField;
        }
        set
        {
            this.prcpabv14dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpblw14d
    {
        get
        {
            return this.prcpblw14dField;
        }
        set
        {
            this.prcpblw14dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpabv30d
    {
        get
        {
            return this.prcpabv30dField;
        }
        set
        {
            this.prcpabv30dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpblw30d
    {
        get
        {
            return this.prcpblw30dField;
        }
        set
        {
            this.prcpblw30dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpabv90d
    {
        get
        {
            return this.prcpabv90dField;
        }
        set
        {
            this.prcpabv90dField = value;
        }
    }
    
    /// <remarks/>
    public bool prcpblw90d
    {
        get
        {
            return this.prcpblw90dField;
        }
        set
        {
            this.prcpblw90dField = value;
        }
    }
    
    /// <remarks/>
    public bool precipa_r
    {
        get
        {
            return this.precipa_rField;
        }
        set
        {
            this.precipa_rField = value;
        }
    }
    
    /// <remarks/>
    public bool sky_r
    {
        get
        {
            return this.sky_rField;
        }
        set
        {
            this.sky_rField = value;
        }
    }
    
    /// <remarks/>
    public bool temp_r
    {
        get
        {
            return this.temp_rField;
        }
        set
        {
            this.temp_rField = value;
        }
    }
    
    /// <remarks/>
    public bool td_r
    {
        get
        {
            return this.td_rField;
        }
        set
        {
            this.td_rField = value;
        }
    }
    
    /// <remarks/>
    public bool wdir_r
    {
        get
        {
            return this.wdir_rField;
        }
        set
        {
            this.wdir_rField = value;
        }
    }
    
    /// <remarks/>
    public bool wspd_r
    {
        get
        {
            return this.wspd_rField;
        }
        set
        {
            this.wspd_rField = value;
        }
    }
    
    /// <remarks/>
    public bool wwa
    {
        get
        {
            return this.wwaField;
        }
        set
        {
            this.wwaField = value;
        }
    }
    
    /// <remarks/>
    public bool wgust
    {
        get
        {
            return this.wgustField;
        }
        set
        {
            this.wgustField = value;
        }
    }
    
    /// <remarks/>
    public bool iceaccum
    {
        get
        {
            return this.iceaccumField;
        }
        set
        {
            this.iceaccumField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ndfdXMLPortTypeChannel : ndfdXMLPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ndfdXMLPortTypeClient : System.ServiceModel.ClientBase<ndfdXMLPortType>, ndfdXMLPortType
{
    
    public ndfdXMLPortTypeClient()
    {
    }
    
    public ndfdXMLPortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ndfdXMLPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ndfdXMLPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ndfdXMLPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string NDFDgen(decimal latitude, decimal longitude, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters)
    {
        return base.Channel.NDFDgen(latitude, longitude, product, startTime, endTime, Unit, weatherParameters);
    }
    
    public System.Threading.Tasks.Task<string> NDFDgenAsync(decimal latitude, decimal longitude, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters)
    {
        return base.Channel.NDFDgenAsync(latitude, longitude, product, startTime, endTime, Unit, weatherParameters);
    }
    
    public string NDFDgenLatLonList(string listLatLon, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters)
    {
        return base.Channel.NDFDgenLatLonList(listLatLon, product, startTime, endTime, Unit, weatherParameters);
    }
    
    public System.Threading.Tasks.Task<string> NDFDgenLatLonListAsync(string listLatLon, string product, System.DateTime startTime, System.DateTime endTime, string Unit, weatherParametersType weatherParameters)
    {
        return base.Channel.NDFDgenLatLonListAsync(listLatLon, product, startTime, endTime, Unit, weatherParameters);
    }
    
    public string LatLonListSubgrid(decimal lowerLeftLatitude, decimal lowerLeftLongitude, decimal upperRightLatitude, decimal upperRightLongitude, decimal resolution)
    {
        return base.Channel.LatLonListSubgrid(lowerLeftLatitude, lowerLeftLongitude, upperRightLatitude, upperRightLongitude, resolution);
    }
    
    public System.Threading.Tasks.Task<string> LatLonListSubgridAsync(decimal lowerLeftLatitude, decimal lowerLeftLongitude, decimal upperRightLatitude, decimal upperRightLongitude, decimal resolution)
    {
        return base.Channel.LatLonListSubgridAsync(lowerLeftLatitude, lowerLeftLongitude, upperRightLatitude, upperRightLongitude, resolution);
    }
    
    public string LatLonListLine(decimal endPoint1Lat, decimal endPoint1Lon, decimal endPoint2Lat, decimal endPoint2Lon)
    {
        return base.Channel.LatLonListLine(endPoint1Lat, endPoint1Lon, endPoint2Lat, endPoint2Lon);
    }
    
    public System.Threading.Tasks.Task<string> LatLonListLineAsync(decimal endPoint1Lat, decimal endPoint1Lon, decimal endPoint2Lat, decimal endPoint2Lon)
    {
        return base.Channel.LatLonListLineAsync(endPoint1Lat, endPoint1Lon, endPoint2Lat, endPoint2Lon);
    }
    
    public string LatLonListZipCode(string zipCodeList)
    {
        return base.Channel.LatLonListZipCode(zipCodeList);
    }
    
    public System.Threading.Tasks.Task<string> LatLonListZipCodeAsync(string zipCodeList)
    {
        return base.Channel.LatLonListZipCodeAsync(zipCodeList);
    }
    
    public string LatLonListCityNames(string displayLevel)
    {
        return base.Channel.LatLonListCityNames(displayLevel);
    }
    
    public System.Threading.Tasks.Task<string> LatLonListCityNamesAsync(string displayLevel)
    {
        return base.Channel.LatLonListCityNamesAsync(displayLevel);
    }
    
    public string LatLonListSquare(decimal centerPointLat, decimal centerPointLon, decimal distanceLat, decimal distanceLon, decimal resolution)
    {
        return base.Channel.LatLonListSquare(centerPointLat, centerPointLon, distanceLat, distanceLon, resolution);
    }
    
    public System.Threading.Tasks.Task<string> LatLonListSquareAsync(decimal centerPointLat, decimal centerPointLon, decimal distanceLat, decimal distanceLon, decimal resolution)
    {
        return base.Channel.LatLonListSquareAsync(centerPointLat, centerPointLon, distanceLat, distanceLon, resolution);
    }
    
    public string CornerPoints(string sector)
    {
        return base.Channel.CornerPoints(sector);
    }
    
    public System.Threading.Tasks.Task<string> CornerPointsAsync(string sector)
    {
        return base.Channel.CornerPointsAsync(sector);
    }
    
    public string GmlLatLonList(string listLatLon, System.DateTime requestedTime, string featureType, weatherParametersType weatherParameters)
    {
        return base.Channel.GmlLatLonList(listLatLon, requestedTime, featureType, weatherParameters);
    }
    
    public System.Threading.Tasks.Task<string> GmlLatLonListAsync(string listLatLon, System.DateTime requestedTime, string featureType, weatherParametersType weatherParameters)
    {
        return base.Channel.GmlLatLonListAsync(listLatLon, requestedTime, featureType, weatherParameters);
    }
    
    public string GmlTimeSeries(string listLatLon, System.DateTime startTime, System.DateTime endTime, string compType, string featureType, string propertyName)
    {
        return base.Channel.GmlTimeSeries(listLatLon, startTime, endTime, compType, featureType, propertyName);
    }
    
    public System.Threading.Tasks.Task<string> GmlTimeSeriesAsync(string listLatLon, System.DateTime startTime, System.DateTime endTime, string compType, string featureType, string propertyName)
    {
        return base.Channel.GmlTimeSeriesAsync(listLatLon, startTime, endTime, compType, featureType, propertyName);
    }
    
    public string NDFDgenByDay(decimal latitude, decimal longitude, System.DateTime startDate, string numDays, string Unit, string format)
    {
        return base.Channel.NDFDgenByDay(latitude, longitude, startDate, numDays, Unit, format);
    }
    
    public System.Threading.Tasks.Task<string> NDFDgenByDayAsync(decimal latitude, decimal longitude, System.DateTime startDate, string numDays, string Unit, string format)
    {
        return base.Channel.NDFDgenByDayAsync(latitude, longitude, startDate, numDays, Unit, format);
    }
    
    public string NDFDgenByDayLatLonList(string listLatLon, System.DateTime startDate, string numDays, string Unit, string format)
    {
        return base.Channel.NDFDgenByDayLatLonList(listLatLon, startDate, numDays, Unit, format);
    }
    
    public System.Threading.Tasks.Task<string> NDFDgenByDayLatLonListAsync(string listLatLon, System.DateTime startDate, string numDays, string Unit, string format)
    {
        return base.Channel.NDFDgenByDayLatLonListAsync(listLatLon, startDate, numDays, Unit, format);
    }
}
