//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/", ConfigurationName="IRandomizerService")]
public interface IRandomizerService {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/IRandomizerService/GetRandomElement")]
    schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString GetRandomElement(schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString list, int number);
}

public interface IRandomizerServiceChannel : IRandomizerService, System.ServiceModel.IClientChannel {
}

public class RandomizerServiceClient : System.ServiceModel.ClientBase<IRandomizerService>, IRandomizerService {
    
    public RandomizerServiceClient() {
    }
    
    public RandomizerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public RandomizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public RandomizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public RandomizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString GetRandomElement(schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString list, int number) {
        return base.Channel.GetRandomElement(list, number);
    }
}
namespace tempuri.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRandomElement", Namespace="http://tempuri.org/")]
    public partial class GetRandomElement : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString listField;
        
        private int numberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRandomElementResponse", Namespace="http://tempuri.org/")]
    public partial class GetRandomElementResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString GetRandomElementResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.microsoft.com._2003._10.Serialization.Arrays.ArrayOfString GetRandomElementResult {
            get {
                return this.GetRandomElementResultField;
            }
            set {
                this.GetRandomElementResultField = value;
            }
        }
    }
}
namespace schemas.microsoft.com._2003._10.Serialization.Arrays {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
}
